### PR TITLE
bb.org: Add Fedora 35 to BB worker image CI

### PR DESCRIPTION
**Pull request by vladbogo**
Add Fedora 35 to CI image creation.

@fauust Am I missing something or is it that simple?

### CODE REVIEW

**Comment by grooverdan** [comment]
Looks that simple. CI built it.

**Comment by cvicentiu** [comment]
Looks nice. One thing to note, is this line then necessary?

https://github.com/MariaDB/mariadb.org-tools/blob/master/buildbot.mariadb.org/ci_build_images/fedora.Dockerfile#L6

**Comment by fauust** [comment]
> Looks nice. @fauust One thing to note, is this line then necessary? It seems that the gihub actions step overrides it anyweay.
> 
> https://github.com/MariaDB/mariadb.org-tools/blob/master/buildbot.mariadb.org/ci_build_images/fedora.Dockerfile#L6

Yes it's still needed for [local builds](https://github.com/MariaDB/mariadb.org-tools/blob/master/buildbot.mariadb.org/ci_build_images/README.md#manually-build-containers).

**Comment by fauust** [comment]
> Add Fedora 35 to CI image creation.
> 
> @fauust Am I missing something or is it that simple?

You may want to add `RHEL_ORGID` and `RHEL_KEYNAME` to your fork secret. This way, it would build also RHEL images.
When everything is green, we can merge and it will push to quay.io.

**Comment by fauust** [comment]
> Looks nice. @fauust One thing to note, is this line then necessary to be hardcoded as fedora:34? It seems that the gihub actions step overrides it anyway. Perhaps we can make it such that it fails if fedora number isn't specified so we have a sort-of "failing test" if we misconfigured the CI pipeline. The last thing we want is for us to have a typo in the CI yml and have fedora:34 images when we think we should have fedora 35 and everything be green.
> 
> https://github.com/MariaDB/mariadb.org-tools/blob/master/buildbot.mariadb.org/ci_build_images/fedora.Dockerfile#L6

Here you go:
https://github.com/MariaDB/mariadb.org-tools/pull/86

Failing CI tested:
https://github.com/fauust/mariadb.org-tools/runs/4309631450?check_suite_focus=true

**Comment by fauust** [comment]
> You may want to add `RHEL_ORGID` and `RHEL_KEYNAME` to your fork secret (see https://access.redhat.com/management/activation_keys). This way, it would build also RHEL images. When everything is green, we can merge and it will push to quay.io.

@vladbogo I believe that is something strange with secrets as they seem to be present on the repo but still CI complains. I will check that. Can you rebase and push again (I have merged #86).

**Review by fauust — APPROVED** [review]

**Comment by vladbogo** [comment]
I added the secrets but doesn't seem to solve the issue. 

Maybe this is why: "Secrets are not passed to workflows that are triggered by a pull request from a fork."

**Comment by fauust** [comment]
> Maybe this is why: "Secrets are not passed to workflows that are triggered by a pull request from a fork."

Yep but if Secrets are in your fork settings plus in the master repo then this is not a normal situation. Anyway, let's merge and see next time if we have the same problem.

**Pull request merged**
