### PR TITLE
bb.org: Add missing Galera deps

### PR DESCRIPTION
**Pull request by vladbogo**
Add Galera builders missing deps

### CODE REVIEW

**Comment by cvicentiu** [comment]
Looks good to me.

**Comment by fauust** [comment]
Hi!
You have added 2 unnecessary deps:
- `libboost-dev`;
- `libboost-filesystem-dev`.

There are already included by the `debian/control` file (see [10.5](https://github.com/MariaDB/server/blob/10.5/debian/control#L16-L17) and [10.7](https://github.com/MariaDB/server/blob/10.7/debian/control#L16-L17)).
The only remaining that is not included dynamically is `libboost-program-options-dev` and I am wondering why it is needed then...

Please be careful when adding dependencies, also please add in the commit message the build log error so we can track better why a dependency was added.

**Comment by vladbogo** [comment]
Hi. I got the list from @cvicentiu after he did a lot of debugging. 

Please note that this applies to the Galera builds. I agree that _libboost-dev_ is already in the control, but _libboost-filesystem-dev_ seems to be only required for amd64 while we also need it for other arches.

Maybe it would make sense to have a separate Docker image for the Galera builders though, but this implies even more dependencies to manage.

However, the setup where we have both the deps from control and a separate list of additional deps is not ideal from my point of view. I think that you should be able to easily see what are the installed packages and in the current way it's easy to get confused.

**Comment by cvicentiu** [comment]
@fauust, galera builds require it. See https://github.com/MariaDB/galera/blob/mariadb-4.x/debian/control

I also agree with @vladbogo, I do not like us fetching deps from 2 different lists (build-deps and individually maintained). This is the kind of confusion that happened when Otto introduced the idea the first time around.

I think we should figure out a way to have a single place where we list all dependencies (maybe straight within Dockerfile is the best). This should be a dedicated discussion. Let's set up an MDBF task for this and figure out the proper way forward.

**Comment by cvicentiu** [comment]
Also, agree with @fauust that we need to improve commit messages. :)

**Comment by fauust** [comment]
I just don't want us to re-introduce the mess that we had before and would like us to keep this dependency thing simple. Also there is maybe a good thing to do to manage these in a generic way for all OSes.

Yep let's discuss and improve it. I am open to any suggestion that can make this Dockerfile management as simple as possible. Also it would be good to have a way to remove no more used dependencies in the future.

**Pull request merged**
