### PR TITLE
Remove cleanup that is not needed

### PR DESCRIPTION
**Pull request by fauust**
The cleanup command is useless:
- docker container are not reused
- libvirt VM are always clean (qemu hook)

@vladbogo I am not sure about nonlatent workers but we probably only need the cleanup step for them?

### CODE REVIEW

**Comment by vladbogo** [comment]
In theory we do not need them. The cleanup step is needed for Windows only at this point (and this PR doesn't change that). However, this is very dependent on ensuring that we always pass build_wait_timeout=0 to the builders. Otherwise, buildbot will not shut down the worker. For libvirt it doesn't make sense since it is not complete, but for the Docker workers it ensures that the environment has no left over files and acts as a safe mechanism. In theory we can increase the build_wait_timeout and use the same container for more builds, but I am not sure if this is a good idea. Anyway, I guess we can remove it, but we need to double check that build_wait_timeout=0 is passed everywhere before.

**Comment by vladbogo** [comment]
I found some cases where build_wait_timeout=0 is not passed (https://github.com/MariaDB/mariadb.org-tools/blob/91c1e5fbd2a96000f52174ef6b7f3527f44ee6f0/buildbot.mariadb.org/master.cfg#L309, https://github.com/MariaDB/mariadb.org-tools/blob/91c1e5fbd2a96000f52174ef6b7f3527f44ee6f0/buildbot.mariadb.org/master.cfg#L408). @fauust do you change that as well or do you want me to handle it?

**Comment by fauust** [comment]
> In theory we can increase the build_wait_timeout and use the same container for more builds, but I am not sure if this is a good idea.

Ok, I have just take a look at https://docs.buildbot.net/current/manual/configuration/workers.html, this is a nice feature but I agree, this seems not a good scenario for us. I can't see a scenario where this could be a good idea. Worker preparation is a very fast step and this ensure that the container is perfectly clean. With regard to libvirt, this is of course not an option...

> do you change that as well or do you want me to handle it?

It make sense to handle this in this PR since it's closely related to it. I am wondering if we should not create a variable with all mandatory/default options in order to be sure to not forget this when we define new worker, can we do that in python?

**Comment by vladbogo** [comment]
The best solution from my point of view would be to use the addWorker function everywhere

**Comment by fauust** [comment]
As discussed with @vladbogo, this is part of a bigger rewriting that will be done in the new repo.

**Pull request closed without merging**
