### PR TITLE
bb.org break out rpm and deb scripts

### PR DESCRIPTION
**Pull request by grooverdan**
Should fix rpm-autobake-install error too:

```
+ sudo sh -c 'g=/usr/lib*/galera*/libgalera_smm.so; echo -e "[galera]
wsrep_provider=$g"'
bash: line 53: /etc/my.cnf.d/galera.cnf: Permission denied
```

If this is the way you want to continue, need to follow with deb scripts.

### CODE REVIEW

**Comment by vladbogo** [comment]
Hi,

I think overall the PR looks good. However, @cvicentiu told me that we will move the scripts directly into the server repo. Did you talk with him anything related to this aspect?

Cheers!

**Comment by grooverdan** [comment]
Nope,  individual effort.

**Comment by vladbogo** [comment]
As I said, the PR looks good. From my point of view you can feel free to merge it, but I think it maybe it might be useful to sync with @cvicentiu and move the scripts directly to the server repo.

**Comment by cvicentiu** [comment]
Let's move the files as is for now in buildbot config, test it out then we
move them to server repo. That might take a few more days.

**Comment by grooverdan** [comment]
> Let's move the files as is for now in buildbot config

I'm slightly confused by "move" "as is", but I'm reading this as a merge. Apologizes if I got this wrong.

**Pull request merged**
