### PR TITLE
bb.org: verbose f_quick_builds

### PR DESCRIPTION
**Pull request by grooverdan**
Trying to read how cmake is constructing the compile line for each file
is obsecured in its current form. The make output by default interleaves
the output from a previous build target with the warnings from another.

Trying to work out why specific cflags aren't added in resolving issues
like MDEV-27936 make development feel like guesswork.

Using the cmake --build . --verbose, the build becomes clever enough
to show the build commmand line, followed by the output it generates.

As an addition, lets also show of the ccache stats associated with the
build.

I know our bandwidth io is strained, but the ability to use outputs to resolve cmake based changes is hard.

by comparision, debians https://buildd.debian.org/status/fetch.php?pkg=mariadb-10.6&arch=ppc64el&ver=1%3A10.6.7-1&stamp=1646197860&raw=0, despite the lack of --output-sync=target are pretty easy to see what is going on.

### CODE REVIEW

**Comment by cvicentiu** [comment]
Typo in `--verbose` in the command line.

Typo in `obsecured` commit message.
Typo in `show of` commit message.

Looks good to me. I think our bandwidth is actually limited by "line numbers", not "line lengths". So this should probably still be ok.

**Comment by fauust** [comment]
Some quick comments about ccache.

I discovered yesterday that on Debian, the following was needed for ccache to be populated (sbuild and chroot env context):
```bash
update-ccache-symlinks
```

and this of course (that is already done):
```bash
export PATH="/usr/lib/ccache:$PATH"
export CCACHE_DIR="/directory/of/ccache"
```

So I am not sure if it's needed, what is sure is that we need to proper monitor ccache utilization as it enormously speed up the build process.

We discussed this with @vladbogo yesterday, I don't have a good idea so far but we should be alerted if `ccache -s` output is not satisfactory (no idea what the threshold is though).

**Comment by grooverdan** [comment]
The use of `CMAKE_{LANG}_COMPILER_LAUNCHER` shouldn't need any `update-ccache-symlinks`. the compiler can be real and the launcher is used by cmake.

I agree with paths probably not needed.

**Comment by vladbogo** [comment]
LGTM as well. Anything else that needs to be done or can it be merged?

**Comment by grooverdan** [comment]
its ready

**Pull request merged**
