### PR TITLE
MDBF-404: Add tagging to README.md

### PR DESCRIPTION
**Pull request by illuusio**
Add tagging to 'manually build containers' instructions so it'll easier to use builded images

### CODE REVIEW

**Comment by fauust** [comment]
Yep, why not! Plus I guess that if we merge this first PR, then you will not need us to approve for the CI to run. So let's do it!

**Comment by fauust** [comment]
I have canceled the CI run since there is no reason to push new images on quay.io with this merge (and I should improve the CI to skip the run if only documentation is modified).

**Comment by grooverdan** [comment]
[[skip ci]](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/)

**Comment by fauust** [comment]
> [[skip ci]](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/)

Yep, I was thinking on something more automatic with https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters

**Pull request merged**
